spring:
  datasource:
    master:
      jdbcUrl: jdbc:mysql://localhost:3306/mall_db?useSSL=false&serverTimezone=UTC
      username: root
      password: mqw12345
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbcUrl: jdbc:mysql://localhost:3306/mqw-blog?useSSL=false&serverTimezone=UTC
      username: root
      password: mqw12345
      driver-class-name: com.mysql.cj.jdbc.Driver
